spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ourmenu?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: misa150901
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  swagger:
    #server-url: http://localhost:8080
    #server-url: https://bluesparrow.shop
  logging:
    level:
      org.hibernate.SQL: debug


