spring:
  datasource:
    url: jdbc:mysql://localhost:${PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  swagger:
    #server-url: http://localhost:8080
    #server-url: https://bluesparrow.shop
  data:
    mongodb:
      url: ${MONGO_URL}
      #uri: ${MONGO_URL}
  logging:
    level:
      org.hibernate.SQL: debug


